describe("Manager", function () {
    require("./deposit")
    require("./whenAllDepositsMade")
    require("./createNFT")
    require("./createMetadata")
    require("./updateRarityGroups")
    require("./updateTokenFee")
    require("./updateLockedPeriod")
    require("./withdrawTokens")
})
