describe("Manager", function () {
    require("./Manager_deposit")
    require("./Manager_whenAllDepositsMade")
    require("./Manager_createNFT")
    require("./Manager_createMetadata")
    require("./Manager_updateRarityGroups")
    require("./Manager_updateTokenFee")
    require("./Manager_updateLockedPeriod")
    require("./Manager_withdrawTokens")
})
